Added deserialization by rowGroupIndex
aloneguid/parquet-dotnet pull request #330
Opened 2023-05-11 09:54 UTC by mcbos

…on https://github.com/aloneguid/parquet-dotnet/issues/329

2023-05-11 10:14 UTC, aloneguid requested changes

2023-05-11 10:14 UTC, aloneguid commented on docs/serialisation.md
> +IList<Record> data = await ParquetSerializer.DeserializeByRowGroupAsync<Record>("/mnt/storage/data.parquet", rowGroupIndex);
`DeserializeByRowGroupAsync` method doesn't seem to exist.

2023-05-11 10:14 UTC, aloneguid commented on docs/serialisation.md
> -Class serialisation philosophy is based on the idea that we don't need to reinvent the wheel when it comes to converting objects to and from JSON. Instead of creating our own custom serialisers and d
It's `deserialise` in British English, so no big deal ;) Methods are called with `z` just to look similar to other methods in .net.

2023-05-11 10:14 UTC, aloneguid commented on src/Parquet/Serialization/ParquetSerializer.cs
> +            int rowGroupIndex,
might be worth adding after `options` parameter and give it a default value, that way it's minimum breaking changes.

2023-05-11 10:14 UTC, aloneguid commented on src/Parquet/Serialization/ParquetSerializer.cs
> +        {
Formatting seems to be broken in a few places. I'm not sure your editor/IDE supports `.editorconfig` which is configured with preferred rules for this project.

2023-05-11 10:48 UTC, mcbos commented on src/Parquet/Serialization/ParquetSerializer.cs
> +            int rowGroupIndex,
I'm using method overloading to not break current functionality.

See [line 140](https://github.com/mcbos/parquet-dotnet/blob/deserialize-by-rowgroup/src/Parquet/Serialization/ParquetSerializer.cs#L140).

2023-05-11 10:48 UTC, mcbos commented on src/Parquet/Serialization/ParquetSerializer.cs
> +        {
Rider was doing strange things, hope its better now.

2023-05-12 08:00 UTC, aloneguid approved these changes
lgtm, thanks!

2023-05-16 13:43 UTC, merged