Now is possible use other attribute to ignore field without lost the …
aloneguid/parquet-dotnet pull request #511
Opened 2024-05-17 12:03 UTC by rhvieira1980

…json serialization option in the POCO.

resolved by: #1

2024-05-22 11:15 UTC, aloneguid requested changes

2024-05-22 11:15 UTC, aloneguid commented on src/Parquet/Serialization/Attributes/ParquetIgnoreFieldAttribute.cs
> +    public class ParquetIgnoreFieldAttribute : Attribute {
As we already have `[ParquetRequired]` it's probalby better to name this `ParquetIgnoreAttribute`?

2024-05-22 11:18 UTC, aloneguid commented
You might also want to add a unit test for this attribute to avoid it being broken in future.

2024-05-22 11:25 UTC, rhvieira1980 commented
In this case the attribute is made to Ignore, not to require.

This usually use if you want to serialize the attribute in json, but not in parquet .

Best

________________________________
De: Ivan G ***@***.***>
Enviado: quarta-feira, 22 de maio de 2024 08:16
Para: aloneguid/parquet-dotnet ***@***.***>
Cc: Rafael Vieira ***@***.***>; Author ***@***.***>
Assunto: Re: [aloneguid/parquet-dotnet] Now is possible use other attribute to ignore field without lost the … (PR #511)


@aloneguid requested changes on this pull request.

________________________________

In src/Parquet/Serialization/Attributes/ParquetIgnoreFieldAttribute.cs<https://github.com/aloneguid/parquet-dotnet/pull/511#discussion_r1609765533>:

> @@ -0,0 +1,14 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Parquet.Serialization.Attributes {
+
+    /// <summary>
+    /// Attribute to Ignore Field in Serialization, some times need data in json but not need in parquet.
+    /// </summary>
+    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
+    public class ParquetIgnoreFieldAttribute : Attribute {


As we already have [ParquetRequired] it's probalby better to name this ParquetIgnoreAttribute?

—
Reply to this email directly, view it on GitHub<https://github.com/aloneguid/parquet-dotnet/pull/511#pullrequestreview-2070892391>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AONHYJZLQLBAUAQGQ4SFR63ZDR47HAVCNFSM6AAAAABH4AI5JWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZQHA4TEMZZGE>.
You are receiving this because you authored the thread.

2024-05-22 11:35 UTC, rhvieira1980 commented on src/Parquet/Serialization/Attributes/ParquetIgnoreFieldAttribute.cs
> +    public class ParquetIgnoreFieldAttribute : Attribute {
ok, Now I understand that you said

2024-05-24 13:47 UTC, aloneguid approved these changes
Looks fine, thanks! It will be included in the current pre-release version.

2024-05-24 13:47 UTC, merged